## THIS IS LICENCED UNDER TECHXPLOIT.COM.NG.................
## ANY MODIFICATION TO THIS FILE REQUIRES APPROVAL.........

## THIS CONFIGURATION IS FOR THE ON GROUND SERVER FOR FMC ABEOKUTA........
## REFER TO CLOUD FOLDER FOR CLOUD COMPOSE FILES................


version: "3"
services:

  nginx:
    image: orthancteam/orthanc-nginx:24.9.1
    depends_on: [orthanc, orthanc-auth-service, orthanc-for-api, meddream-viewer, keycloak]
    restart: unless-stopped
#    ports: ["8080:80"]
# if setting ENABLE_HTTPS: "true" env var, uncomment the following 4 lines and comment the line with 'ports: ["80:80"]'
    ports: ["443:443"]
    volumes:
      - /home/holyfire/finalsetup/sslkeys/crt.pem:/etc/nginx/tls/crt.pem
      - /home/holyfire/finalsetup/sslkeys/key.pem:/etc/nginx/tls/key.pem
    environment:
      ENABLE_ORTHANC: "true"
      ENABLE_KEYCLOAK: "true"
      ENABLE_OHIF: "true"
      ENABLE_ORTHANC_TOKEN_SERVICE: "true"
      ENABLE_HTTPS: "true"
      ENABLE_MEDDREAM: "true"
      ENABLE_WSI: "true"
      ENABLE_ORTHANC_FOR_API: "true"

  orthanc:
    image: orthancteam/orthanc:24.9.1-full
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
      - /home/holyfire/finalsetup/custom.css:/home/custom/custom.css
      - /home/holyfire/finalsetup/logo.png:/home/custom/logo.png
      - /home/holyfire/finalsetup/favicon.ico:/home/custom/favicon.ico

    depends_on: [orthanc-db]
    ports: ["4242:4242", "8042:8042"]
    restart: unless-stopped
    environment:
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__POSTGRESQL__HOST: "orthanc-db"
      ORTHANC__POSTGRESQL__ENABLE_INDEX: "true"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      HOUSEKEEPER_PLUGIN_ENABLED: "true"
      DELAYED_DELETION_PLUGIN_ENABLED: "true"
      NEURO_PLUGIN_ENABLED: "true"
      WSI_PLUGIN_ENABLED: "true"
      CONNECTIVITY_CHECKS_PLUGIN_ENABLED: "true"
      WORKLISTS_PLUGIN_ENABLED: "true"
      TCIA_PLUGIN_ENABLED: "true"
      VOLVIEW_PLUGIN_ENABLED: "true"
      ORTHANC__PYTHON_VERBOSE: "true"
      ORTHANC__PYTHON_PLUGIN_ENABLED: "true"
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"
      ORTHANC__POSTGRESQL__INDEX_CONNECTIONS_COUNT: 10
      ORTHANC__POSTGRESQL__TRANSACTION_MODE: "ReadCommitted"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__ENABLE_SHARES: "true"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__STUDY_LIST_SEARCH_MODE: "search-button"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__SHOW_SAME_PATIENT_STUDIES_FILTER: '["PatientBirthDate"]'
      ORTHANC_JSON: |
        {
          "Name": "FMCA MAIN SERVER 1",
          "StorageCompression" : false,
          "MaximumStorageSize" : 0,
          "MaximumPatientCount" : 0,
          "MaximumStorageCacheSize" : 128,
          "MaximumStorageMode" : "Recycle",
          "HttpServerEnabled" : true,
          "HttpPort" : 8042,
          "LuaHeartBeatPeriod" : 0,
          "LuaScripts" : [
          ],
          "ConcurrentJobs" : 8,
          "JobsEngineThreadsCount" : {
            "ResourceModification": 1
          },
          "WebDavEnabled" : true,
          "WebDavDeleteAllowed" : false,
          "WebDavUploadAllowed" : true,
          "DicomServerEnabled" : true,
          "StoneWebViewer": {
            "DateFormat" : "DD/MM/YYYY",
            "ShowNotForDiagnosticUsageDisclaimer": false,
            "ShowInfoPanelAtStartup": "Never"
          },
          "OsimisWebViewer1": {
            "DateFormat" : "DD/MM/YYYY",
            "ShowNotForDiagnosticUsageDisclaimer": false,
            "ShowInfoPanelAtStartup": "Never"
          },
          "DicomAet" : "SERVERMAIN1",
          "DicomCheckCalledAet" : true,
          "DicomPort" : 4242,
          "DefaultEncoding" : "Latin1",
          "AcceptedTransferSyntaxes" : [ "1.2.840.10008.1.*" ],
          "UnknownSopClassAccepted" : false,
          "DicomScpTimeout" : 30,
          "SslEnabled" : false,
          "SslCertificate" : "certificate.pem",
          "SslMinimumProtocolVersion" : 4,
          "SslVerifyPeers" : false,
          "SslTrustedClientCertificates" : "trustedClientCertificates.pem",
          "DicomTlsEnabled" : false,
          "DicomTlsRemoteCertificateRequired" : true,
          "DicomAlwaysAllowEcho" : true,
          "DicomAlwaysAllowStore" : true,
          "DicomAlwaysAllowFind" : true,
          "DicomAlwaysAllowFindWorklist" : true,
          "DicomAlwaysAllowGet" : true,
          "DicomAlwaysAllowMove" : true,
          "DicomCheckModalityHost" : false,
          "DicomModalities" : {
            "SANTEPACS" : [ "SANTESRVPG1", "192.168.43.230", 11122],
            "CT-1" : [ "RADIANT", "192.168.43.11", 11112],
            "CT-ROOM2" : [ "efilm", "192.168.43.36", 4006],
            "Dental-x-ray" : [ "DENTALMAIN", "192.168.43.9", 104],
            "Eye-fundus-Camera" : [ "fmcac3", "192.168.0.184", 11118],
            "Eye-OCT" : [ "fmcac4", "192.168.0.184", 11119],
            "Echo-machine-1" : [ "fmcac5", "192.168.0.194", 11110],
            "Echo-machine-2" : [ "fmcac5", "192.168.0.194", 1100],
            "ECG-Machine" : [ "fmcac6", "192.168.0.64", 11111],
            "Endoscopy-machine" : [ "fmcac7", "192.168.0.140", 11112],
            "Mamography" : [ "fmcac8", "192.168.0.133", 11113],
            "US-1" : [ "fmcac9", "192.168.0.187", 1114],
            "US-2" : [ "fmcac10", "192.168.0.14", 2222],
            "US-3" : [ "fmcac17", "192.168.0.200", 1826],
            "x-ray" : [ "fmcac11", "192.168.43.10", 2323],
            "Fluoroscopy" : [ "fmcac12", "192.168.43.190", 2424]
          },
          "DicomModalitiesInDatabase" : false,
          "DicomEchoChecksFind" : false,
          "DicomScuTimeout" : 10,
          "DicomScuPreferredTransferSyntax" : "1.2.840.10008.1.2.1",
          "DicomThreadsCount" : 4,
          "OrthancPeers" : {
            "CLOUD_SERVER" : [ "https://www.techxploit.com.ng/" ],
            "PUBLIC_SERVER" : [ "http://192.168.43.195:8042/" ]
          },
          "OrthancPeersInDatabase" : false,
          "HttpProxy" : "",
          "HttpVerbose" : false,
          "HttpTimeout" : 60,
          "HttpsVerifyPeers" : true,
          "HttpsCACertificates" : "/etc/ssl/certs/ca-certificates.crt",
          "UserMetadata" : {
            // "Sample" : 1024
          },
          "UserContentType" : {
            // "sample" : 1024
            // "sample2" : [ 1025, "application/pdf" ]
          },
          "StableAge" : 60,
          "StrictAetComparison" : false,
          "StoreMD5ForAttachments" : true,
          "LimitFindResults" : 0,
          "LimitFindInstances" : 0,
          "LogExportedResources" : false,
          "KeepAlive" : true,
          "TcpNoDelay" : true,
          "HttpThreadsCount" : 50,
          "StoreDicom" : true,
          "DicomAssociationCloseDelay" : 5,
          "QueryRetrieveSize" : 100,
          "CaseSensitivePN" : false,
          "LoadPrivateDictionary" : true,
          "Dictionary" : {
          },
          "SynchronousCMove" : true,
          "JobsHistorySize" : 10,
          "SaveJobs" : true,
          "OverwriteInstances" : false,
          "MediaArchiveSize" : 1,
          "StorageAccessOnFind" : "Always",
          "MetricsEnabled" : true,
          "ExecuteLuaEnabled" : false,
          "HttpRequestTimeout" : 30,
          "DefaultPrivateCreator" : "",
          "StorageCommitmentReportsSize" : 100,
          "TranscodeDicomProtocol" : true,
          "BuiltinDecoderTranscoderOrder" : "After",
          "IngestTranscoding" : "1.2.840.10008.1.2.4.70",
          "IngestTranscodingOfUncompressed" : true,
          "IngestTranscodingOfCompressed" : true,
          "DicomLossyTranscodingQuality" : 90,
          "SyncStorageArea" : true,
          "MallocArenaMax" : 5,
          "DeidentifyLogs" : true,
          "DeidentifyLogsDicomVersion" : "2021b",
          "MaximumPduLength" : 16384,
          "CheckRevisions" : false,
          "SynchronousZipStream" : true,
          "ZipLoaderThreads": 0,
          "Warnings" : {
            "W001_TagsBeingReadFromStorage": true,
            "W002_InconsistentDicomTagsInDb": true
          },
          "OrthancExplorer2": {
            "IsDefaultUI": true,
            "Theme": "dark",
            "CustomCssPath": "/home/custom/custom.css",
            "CustomLogoPath": "/home/custom/logo.png",
            "CustomTitle": "FMCA MAIN PACS",
            "CustomFavIconPath": "/home/custom/favicon.ico",
            "UiOptions": {
              "EnableOpenInMedDreamViewer": true,
              "EnableOpenInOhifViewer3": true,
              "EnableStudyList": true,
              "EnableDownloadZip": true,
              "ShowOrthancName": true,
              "MaxStudiesDisplayed": 5000,
              "MaxMyJobsHistorySize": 5,
              "EnableDownloadDicomDir": true,
              "EnableDownloadDicomFile": true,
              "EnableModification": true,
              "DefaultShareDuration": 0,
              "EnableApiViewMenu": true,
              "EnableEditLabels": true,
              "StudyListSearchMode": "search-button",
              "StudyListContentIfNoSearch": "empty",
              "ShareDurations": [0, 7, 15, 30, 90, 365],
              "OhifViewer3PublicRoot": "https://192.168.43.215/ohif/",
              "ViewersIcons" : {
                "osimis-web-viewer": "bi bi-eye",
                "stone-webviewer": "bi bi-eye-fill",
                "ohif": "bi bi-grid",
                "ohif-vr": "bi bi-grid-1x2",
                "ohif-tmtv": "bi bi-grid-3x3-gap",
                "ohif-seg": "fa-solid fa-shapes fa-button",
                "ohif-micro": "fa-solid fa-microscope fa-button",
                "meddream": "bi bi-columns-gap",
                "volview": "bi bi-box",
                "wsi": "fa-solid fa-microscope fa-button"
              },
              "UploadReportTags" : [
                "PatientName",
                "StudyDescription",
                "PatientID",
                "AccessionNumber",
                "StudyDate"
              ],
              "UploadReportMaxTags" : 2,
              "ViewersOrdering" : [
                "osimis-web-viewer",
                "stone-webviewer",
                "ohif",
                "ohif-vr",
                "ohif-tmtv",
                "ohif-seg",
                "ohif-micro",
                "meddream",
                "volview",
                "wsi"
              ],
              "PatientMainTags" : [
                "PatientID",
                "PatientName",
                "PatientBirthDate",
                "PatientSex",
                "OtherPatientIDs"
              ],
              "StudyMainTags" : [
                "StudyDate",
                "StudyTime",
                "StudyDescription",
                "AccessionNumber",
                "StudyID",
                "StudyInstanceUID",
                "RequestingPhysician",
                "ReferringPhysicianName",
                "Department",
                "ReportingDoctor",
                "InstitutionName"
              ],
              "SeriesMainTags" : [
                "SeriesDate",
                "SeriesTime",
                "SeriesDescription",
                "SeriesNumber",
                "BodyPartExamined",
                "ProtocolName",
                "SeriesInstanceUID"
              ],
              "StudyListColumns" : [
                "PatientBirthDate",
                "PatientName",
                "PatientID",
                "StudyDescription",
                "StudyDate",
                "modalities",
                "AccessionNumber",
                "seriesAndInstancesCount"
              ]
            },
            "Tokens" : {
              "InstantLinksValidity": 3600,
              "ShareType": "ohif-viewer-publication"
            },
            "Keycloak" : {
              "Enable": true,
              "Url": "https://192.168.43.215/keycloak/",
              "Realm": "orthanc",
              "ClientId": "orthanc"
            }
          },
          "AuthenticationEnabled": false,     // because it is handled by the authorization plugin
          "Authorization": {
            "WebServiceRootUrl": "http://orthanc-auth-service:8000/",
            "WebServiceSettingsRolesUrl": "http://orthanc-auth-service:8000/",
            "WebServiceUsername": "share-user",
            "WebServicePassword": "change-me",
            "StandardConfigurations" : [
              "osimis-web-viewer",
              "stone-webviewer",
              "orthanc-explorer-2"
            ],
            "CheckedLevel": "studies"
          },
          "DicomWeb": {
            "Enable": true,
            "PublicRoot": "/orthanc/dicom-web/"
          },
          "Housekeeper": {
            "Enable": true,
            "GlobalPropertyId": 1025,
            "Force": false,
            "ThrottleDelay": 5,
            "Schedule": {
              "Monday": ["2-4"],
              "Tuesday": ["2-4"],
              "Wednesday": ["2-4"],
              "Thursday": ["3-5"],
              "Friday": ["3-5"],
              "Saturday": ["22-24"],
              "Sunday": ["22-24"]
            },
            "Triggers" : {
              "StorageCompressionChange": true,
              "MainDicomTagsChange": true,
              "UnnecessaryDicomAsJsonFiles": true
            }
          },
          "WholeSlideImaging" : {
            "EnableIIIF" : true,
            "OrthancPublicURL" : "https://192.168.43.215/orthanc/ui/app",
            "ServeMirador" : true,
            "ServeOpenSeadragon" : true,
            "ForcePowersOfTwoScaleFactors" : true
          },
          "Tcia" : {
            "Enable" : true
          }
        }

  orthanc-auth-service:
    image: orthancteam/orthanc-auth-service:24.7.1
    depends_on: [keycloak, meddream-token-service]
    # permissions can be customized in the permissions.json file
    volumes:
      - ./permissions.jsonc:/orthanc_auth_service/permissions.json
    restart: unless-stopped
    environment:
      SECRET_KEY: "change-me-I-am-a-secret-key"
      ENABLE_KEYCLOAK: "true"
      PUBLIC_ORTHANC_ROOT: "https://192.168.43.215/orthanc/"
      PUBLIC_LANDING_ROOT: "https://192.168.43.215/orthanc/ui/app/token-landing.html"
      USERS: |
        {
          "share-user": "change-me"
        }
      MEDDREAM_TOKEN_SERVICE_URL: "http://meddream-token-service:8088/v3/generate"
      PUBLIC_MEDDREAM_ROOT: "https://192.168.43.215/meddream/"
      PUBLIC_OHIF_ROOT: "https://192.168.43.215/ohif/"

  orthanc-db:
    image: postgres:15
    restart: unless-stopped
    volumes: ["orthanc-db:/var/lib/postgresql/data"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  keycloak:
    image: orthancteam/orthanc-keycloak:24.7.1
    depends_on: [keycloak-db]
    restart: unless-stopped
    volumes:
      - /home/holyfire/finalsetup/images/orthanc-bg.png:/opt/keycloak/themes/orthanc/login/resources/img/orthanc-bg.png
      - /home/holyfire/finalsetup/images/orthanc-logo.png:/opt/keycloak/themes/orthanc/login/resources/img/orthanc-logo.png
      - /home/holyfire/finalsetup/images/orthanc-logo-text.png:/opt/keycloak/themes/orthanc/login/resources/img/orthanc-logo-text.png
      - /home/holyfire/finalsetup/images/orthanc-logo-text-shadow.png:/opt/keycloak/themes/orthanc/login/resources/img/orthanc-logo-text-shadow.png
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "change-me"
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://keycloak-db:5432/keycloak"
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "keycloak"
      KC_HOSTNAME_URL: "https://192.168.43.215/keycloak"
      KC_HOSTNAME_ADMIN_URL: "https://192.168.43.215/keycloak"

  keycloak-db:
    image: postgres:15
    restart: unless-stopped
    volumes: ["keycloak-db:/var/lib/postgresql/data"]
    environment:
      POSTGRES_PASSWORD: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_DB: "keycloak"

  meddream-token-service:
    image: orthancteam/meddream-token-service:24.6.0
    restart: unless-stopped

  ohif:
    image: orthancteam/ohif-v3:24.9.1
#  customize ohif configuration applied
    volumes:
      - ./ohif.js:/usr/share/nginx/html/app-config.js
      - ./ohif-logo.svg:/usr/share/nginx/html/ohif-logo.svg:ro
#      - ./ohif-logo-light.svg:/usr/share/nginx/html/ohif-logo-light.svg:ro
    restart: unless-stopped

  meddream-viewer:
    image: orthancteam/meddream-viewer:24.6.0
    restart: unless-stopped
    depends_on:
      - orthanc-for-api
    environment:
      integration: "study"
      TOKEN_SERVICE_ADDRESS: "https://meddream-token-service:8088/v3/validate"
      ORTHANC_BASE_URL: "https://orthanc-for-api:8042"
      ORTHANC_USER: "meddream-user"
      ORTHANC_PWD: "change-me"
      ORTHANC_MEDDREAM_PYTHON_PLUGIN_ENABLED: "true"
      MEDDREAM_ADMIN_PASSWORD: "change-me"
      MEDDREAM_PACS_CONFIG_TYPE: "Dicomweb"
      ORTHANC_HOSTNAME: "orthanc-for-api"
      ORTHANC_DICOM_PORT: 4242
      ORTHANC_AET: "SERVERMAIN1"
    volumes:
      - meddream-license:/opt/meddream/license

  # An orthanc dedicated for API accesses and also used by MedDream
  orthanc-for-api:
    image: orthancteam/orthanc:24.9.1-full
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
      - ./meddream-plugin.py:/scripts/meddream-plugin.py
    depends_on: [orthanc-db]
    restart: unless-stopped
    environment:
      ORTHANC__NAME: "Orthanc for API"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      ORTHANC__PYTHON_SCRIPT: "/scripts/meddream-plugin.py"
      ORTHANC__AUTHENTICATION_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__DICOM_WEB__PUBLIC_ROOT: "/orthanc-api/dicom-web/"
      ORTHANC__POSTGRESQL__HOST: "orthanc-db"
      ORTHANC_JSON: |
        {
          "RegisteredUsers": {
            "meddream-user": "change-me",
            "script-user": "change-me",
            "dicom-web-client-user": "change-me"
          }
        }


volumes:
  orthanc-storage:
  orthanc-db:
  keycloak-db:
  meddream-license:
