version: "3.3"
services:
  orthanc:
    container_name: orthanc
    image: orthancteam/orthanc:24.12.0
    environment:
      - DICOM_WEB_PLUGIN_ENABLED=true
      - OHIF_PLUGIN_ENABLED=true
    ports:
      - 4242:4242 
      - 8042:8042
    volumes:
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro
      - testdata_db:/var/lib/orthanc/db/
      # - ./ohif.js:/usr/share/nginx/html/app-config.js:ro
    restart: unless-stopped

  ohif_v2:
    image: ohif/viewer
    environment: 
      - APP_CONFIG=/usr/share/nginx/html/app-config.js
    ports:
      - 3000:80
    volumes:
      - ./nginx_ohif.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ohif-v2.js:/usr/share/nginx/html/app-config.js:ro
      - ./logo.png:/usr/share/nginx/html/logo.png:ro
    restart: unless-stopped

  ohif_v3:
    image: ohif/app:v3.9.2
    ports:
      - 3001:80
    volumes:
      - ./nginx_ohif.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ohif-v3.js:/usr/share/nginx/html/app-config.js:ro
    restart: unless-stopped

volumes: 
  testdata_db:
